### ISSUE TITLE
Error on starting up homebridge

### ISSUE THREAD

**Issue by iwanvandaele** [kdb-be/homebridge-telenet-tv-box#1]
Dear,

I've installed the plugin and added the lines to the config file:

{
            "platform": "telenet-tv-box",
            "name": "Telenet TV-box",
            "username": "username",
            "password": "password"
        }

Error on booting homebridge:

4/21/2020, 9:40:32 AM] ====================
[4/21/2020, 9:40:32 AM] ERROR LOADING PLUGIN homebridge-telenet-tv-box:
[4/21/2020, 9:40:32 AM] Error: Cannot find module 'request'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at /homebridge/node_modules/homebridge-telenet-tv-box/node_modules/request-promise/lib/rp.js:11:16
    at module.exports (/homebridge/node_modules/homebridge-telenet-tv-box/node_modules/stealthy-require/lib/index.js:62:23)
    at Object.<anonymous> (/homebridge/node_modules/homebridge-telenet-tv-box/node_modules/request-promise/lib/rp.js:10:19)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/homebridge/node_modules/homebridge-telenet-tv-box/index.js:2:17)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
[4/21/2020, 9:40:32 AM] ====================

[4/21/2020, 9:40:46 AM] Error: The requested platform 'telenet-tv-box' was not registered by any plugin.
    at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:134:13)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:327:45)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:90:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

**Comment by WesleyLiekens** [comment]
I have the same problem. I also work for Telenet. if there is something I could do please let me know

**Comment by WesleyLiekens** [comment]
so I have been looking at the files and compared them to the Ziggo-next plugin...
And it just seems all the words "ziggo" have been replaced with the words "Telenet"
I also see that one of the source links is
https://web-api-prod-obo.horizon.tv/oesp/v3/NL/nld/web/session
horizon is the project name of the ziggo box but the Telenet tv box has another project name...

**Comment by keennandebie** [comment]
> so I have been looking at the files and compared them to the Ziggo-next plugin...
> And it just seems all the words "ziggo" have been replaced with the words "Telenet"
> I also see that one of the source links is
> https://web-api-prod-obo.horizon.tv/oesp/v3/NL/nld/web/session
> horizon is the project name of the ziggo box but the Telenet tv box has another project name...

The API's from all countries work with the horizon.tv link, it just needs to be modified to the right country. It works in every country where they use the Horizon platform (horizon.tv, ziggogo.tv and upctv.ch,...) because they have a login screen on the site itself (you can try it yourself).
However, Telenet decided to make the login process more secure by redirecting to login.prd.telenet.be/openid/login so this plugin won't work. 
I don't know how to make it work with this kind of login so if you could help, that would be amazing.

**Comment by WesleyLiekens** [comment]
Can you tell me what information exactly you would need to get it to work?

Also the projectname is EOS. for telenet

**Comment by keennandebie** [comment]
I have no idea how to bypass this login. The developer of the Ziggo plugin doesn't respond on my question.

**Comment by WesleyLiekens** [comment]
I have sent this to one of the guys from Inhome improvement.
also
Error: The requested platform 'telenet-tv-box' was not registered by any plugin.
this error is not because of the extra login of telenet itself

**Comment by kdb-be** [comment]
True. The plugin has problems with starting up. However, changing the API's on the Ziggo plug in does not do the job either.

**Comment by WesleyLiekens** [comment]
spoken with a guy from Inhome improvement. I don't think this is gonna work... mostly because security issues
maybe you need a new approach.  the controller is working with Zigbee protocol. so might want to use a Zigbee plugin to replace the remote

**Comment by keennandebie** [comment]
This is interesting. Does the box also uses Zigbee and any idea how to set them in pairing mode so the Zigbee gateway can find them?

**Comment by WesleyLiekens** [comment]
Are you Belgian? maybe we should get a private chat up
FB Wesley Liekens
WA 0486045922

**Comment by wvanvlaenderen** [comment]
The issue with the plugin not being loaded should be fixed in #2 
The plugin is still not working due to not being able to authenticate towards https://web-api-prod-obo.horizon.tv/oesp/v3/NL/nld/web/session (HTTP 500)

**Comment by kdb-be** [comment]
This will never works since Telenet uses another login mode than the other companies.

**Comment by mcielen** [comment]
I'm testing as well. Doesn't work, but @kdb-be, could you elaborate? I'm seeing the session url in "network' under developer tools when looking at the telenettv.be web traffic.

**Comment by modparts** [comment]
any progress

**Comment by arkadicolson** [comment]
Does this work with all Telenet boxes? Also the old ones? Is there any specific configuration needed on the Digicorder?

**Comment by JonasVanduffel** [comment]
Are there any updates on this issue?

**Comment by Maffiow** [comment]
same issue over here:

Error loading platform requested in your config.json at position 4
[1/13/2021, 1:05:11 AM] Error: The requested platform 'telenet-tv-box' was not registered by any plugin.
    at PluginManager.getPluginForPlatform (/usr/local/lib/node_modules/homebridge/src/pluginManager.ts:224:15)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:387:37
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:374:27)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:153:29)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47

**Comment by keennandebie** [comment]
This plugin will never work. Telenet has an extra layer of security compared to other daughter companies.

**Comment by WesleyLiekens** [comment]
Someone "from the inside" is working on that 😀

**Comment by Wilmaxe** [comment]
@WesleyLiekens So maybe we will get a working Hombridge plugin for the Telenet TV Box soon?

**Comment by WesleyLiekens** [comment]
I can confirm a successful logon has been achieved and that its being implemented into the plug-in for further testing

**Comment by Wilmaxe** [comment]
> I can confirm a successful logon has been achieved and that its being implemented into the plug-in for further testing

What do you mean with "for further testing" by the developers of this plug-in or already for those who installed the plug-in on their homebridge? Because I installed the last version today and I get still this error message:
[2/8/2021, 12:55:23 PM] ERROR LOADING PLUGIN homebridge-telenet-tv-box:
[2/8/2021, 12:55:23 PM] Error: Cannot find module 'request'

Please let me know when I can test it again and if I have to modify something in my config file to define this Telenet TV Box platform.

Thanks

**Comment by WesleyLiekens** [comment]
By the developer and his beta testers.

**Comment by WesleyLiekens** [comment]
a working plugin has just been released at

https://github.com/jsiegenthaler/homebridge-eosstb

Ideas for updates and contributions are welcome

**Comment by Wilmaxe** [comment]
> a working plugin has just been released at
> 
> https://github.com/jsiegenthaler/homebridge-eosstb
> 
> Ideas for updates and contributions are welcome

I can confirm this too, installed this new beta plugin and works fine with my Telenet TV Box
